/*
* generated by Xtext
*/
package fr.imag.exschema.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class ExSchemaUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return fr.imag.exschema.xtext.ui.internal.ExSchemaActivator.getInstance().getInjector("fr.imag.exschema.xtext.ExSchema");
	}
	
}
