/*
* generated by Xtext
*/
package fr.imag.exschema.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class ExSchemaOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
