/*
 * generated by Xtext
 */
package fr.imag.exschema.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExSchemaUiModule extends fr.imag.exschema.xtext.ui.AbstractExSchemaUiModule {
	public ExSchemaUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
