/*
 * generated by Xtext
 */
package fr.imag.exschema.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExSchemaRuntimeModule extends fr.imag.exschema.xtext.AbstractExSchemaRuntimeModule {

}
