/*
* generated by Xtext
*/
package fr.imag.exschema.xtext.ui.contentassist;

import fr.imag.exschema.xtext.ui.contentassist.AbstractExSchemaProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ExSchemaProposalProvider extends AbstractExSchemaProposalProvider {

}
