/*
* generated by Xtext
*/
package fr.imag.exschema.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import fr.imag.exschema.xtext.services.ExSchemaGrammarAccess;

public class ExSchemaParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ExSchemaGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected fr.imag.exschema.xtext.parser.antlr.internal.InternalExSchemaParser createParser(XtextTokenStream stream) {
		return new fr.imag.exschema.xtext.parser.antlr.internal.InternalExSchemaParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Schema";
	}
	
	public ExSchemaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ExSchemaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
